apiVersion: ENC[AES256_GCM,data:ywg=,iv:m9rx+i2Egrt0r3FZozfw0M2A6OuSmCs1ixMswnHlSTY=,tag:uWCEZtxs/B2sw1n1Ai7QEQ==,type:str]
kind: ENC[AES256_GCM,data:wwxCaS10,iv:Bx6aKbVGNt8foXD1PD2OJh/wjoXh1BQ6V9rlsJcX4AU=,tag:nCO65jkNYlEVlUprC811zQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:OZzFAPr3sPFZ9bKDNdIV6EWWdg==,iv:i0z4WudNhlFafmo5Vtyavc+TL9I2rHqYr9mohyfM86o=,tag:2bzhCKhoh7ccqIT5xbYMzg==,type:str]
    namespace: ENC[AES256_GCM,data:6DsThWwXwSf32g==,iv:JlemoPfIlYcGuuXrFYbIa2EfU959vXl8TkoA5Z/DUl4=,tag:r9mcGpwVqXo4/iIkdo5L4w==,type:str]
stringData:
    GITHUB_TOKEN: ENC[AES256_GCM,data:eaeow6vbDkQMCMCqFzHdbRbnMMgsrAsOd0Z0IrPrhLtsPFTcGJ8X0A==,iv:95YW3293FLazl4Fpn8jPNjnnRQ2rgEvhnO1rVz4NEdA=,tag:ZC5UwlJcRuivYDxlpH1Jyw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiVVRUY1lWRm5uMTAxUTlX
            amcrL21TZThwN2prbzUzcXR3TjdmZFFVWlZrClB4OFhoV1gza0xTd1VYWlVncVFo
            czRFTzJMc2pSanVhVC9hcTd3M29BUkkKLS0tIGlBOFdjVG12blhreFlMQ2xjU2xJ
            eHkwU1BvSGJrcUw3M0NaQW5CZ1NqaXcKtSkSdHhD9wH7gIzWJLqSuc5o79tmFd6c
            3iva1ZwopxVhZui4s4DvWbgX2RwYQYYuGL1pgOw0R6n3dD1YWuYXhQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x5del8md896v3a53z89hss5ktjd0qq4cqlazjd6dkvewjxwy4ufse75yjy
    lastmodified: "2026-07-14T20:18:14Z"
    mac: ENC[AES256_GCM,data:KxhaTCEGtm2BkBS7JOmOhbye+chec3Dn/rGwEn+W1X07/3NIXzRFKb4EzJZrQ7BExCYpxC3J4AZ6lFAOma+1SeBCbqPTMi1rgGdm1bCaKaDQxB9B/EJYz0f0KpMNEa5JK2qEQz+kczEr2IZbdTNyDjxmt72YUt5pPjQXv2LjyNM=,iv:ZOAZ90r20eZQR1FuX1zK5x/JJDboJBMxkjjjGJiTreU=,tag:A6bMTCjXDz7okYGLE/alog==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
