apiVersion: ENC[AES256_GCM,data:vaQ=,iv:4F889ZtCfrqHmDN7dEkKux1RHA1QtGlaXl/OcDu8uKU=,tag:2G4Mh4yuIP34KNmWrCwu4g==,type:str]
kind: ENC[AES256_GCM,data:FI9h4Wpx,iv:4dkvmB5OQW9a+ZqF/eAy2W0VFFL0wkJnLFzWaJfRtrE=,tag:5wz3m6WJ8P4wHnJIhCvJxQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Gjwe0HW2rsChj87duLdOhX09Sr7f,iv:8q1ZDNpKS4YX388xwlB/FWQrlaC8JsW8/I95YE0TQ7k=,tag:egfLDRpkJZ8gEcC2SAehhQ==,type:str]
    namespace: ENC[AES256_GCM,data:mbAZOWw7Q1wa5w==,iv:MHtRRxPqa8XvuC1uUUHH89rfDCIMFhKrvWc2PKJt534=,tag:/HUry66kJzYRJcf1n12ZvA==,type:str]
stringData:
    GITHUB_TOKEN: ENC[AES256_GCM,data:qkvYK6AbLDB3SMw3q7tHeP96HN7qrY8qd76LBMn2O2dzOPLS4zuplfzJhjdC8HzWCHbYBxDEWOT6Fhg4f4ZUNLEzK/j5R0qyBRxoXgyrqNTlVqUrALSEqdZUc8/w,iv:86jarmhFy99xWoaJmAfYOp+qRkl3SY/7vI5jKMCFmv8=,tag:eDI0eVtRLPXdI1J+ISq+FQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5NFZ3UHlxeEVxNFRTR0xz
            c1JxWWtaL1JWYnpZS3ByM2Z3RWt1OVJHL1c4ClIzbThXR2FuL0lhWnZncjY0dElr
            WXUzazJaZ2cvNEhkeG1NK3MxdzVpSVUKLS0tIFhzWHRrQW04aFA4ZVNxYmhQM1do
            SzAzUzdRUEJ0Umd0MnA5OWdTSVlaMkkKZgSdgbTP4WzLbhcI4mOG3k3jS25tve9w
            s70GpH8wt9Ohi1TPQZmcBwpC4YaC6N8ko8XJO2lbpyWs4ilnYCR6AQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x5del8md896v3a53z89hss5ktjd0qq4cqlazjd6dkvewjxwy4ufse75yjy
    lastmodified: "2026-07-06T20:20:53Z"
    mac: ENC[AES256_GCM,data:HWv5tXcuLOxD0bFoje9ugfU4ElsPXz+akdRDZuk8mnjpRstgfjYm4Wov3tBK2kydtS1KtxuJ0EgNhdC0dix2sh+Ub02COuXMgXVwmCJa3CWz9LV1jzyIFjEE5Ql4HJ19jIZPh135EbHrU/zf39MYEkBvAyXiSELI4fWZhVkKlts=,iv:B3iAXb6zQ+vdS7K7R7mG7IxeowWG4fsl9guAmggkfJM=,tag:ydFLVntGYCApZS4bu6Y/kg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
