apiVersion: ENC[AES256_GCM,data:Xlo=,iv:S7Z0TZZKDm5fo3yTaLKm8rvpjpx15RpQaijFV2/B5rc=,tag:RONh/jgo5yHUpqSecnE+JA==,type:str]
kind: ENC[AES256_GCM,data:eA5DJ715,iv:romvad7rMLvMoac+fBnNzD0I5J0u9QeH8teEAdWOsA8=,tag:Es1hdb5n9RR3iVFMCjiE/Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:oztLy2DLzdl+IuaPsgukEyJ9zqM=,iv:D4ZCrBqO/i+Gk7qmG+9Vi/VsCkVUxZ1waiMBnHOkP/Y=,tag:b1dGuit1CHgIDSpPEF566g==,type:str]
    namespace: ENC[AES256_GCM,data:gYmTpGhl0io=,iv:JWNqoOaw8vg4V0IREymwVDJnfLzLL5YR4zpHcqcrDEw=,tag:b8dIbPVJeqdfUz9QonrQcw==,type:str]
stringData:
    password: ENC[AES256_GCM,data:/7tNxP2V0/zCzQUB+5CTWLQUMSIBEgiE7SGdYclsjcPoNbaCnWlZ8VhB4B8=,iv:H8zNm1ITdPSSBf3tTwwqvqBOOcx09O02g7mJ6B4leMY=,tag:k5f9b746eqnmCHACLYZuNw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZWFREcVh6czVmSUg1ZGpH
            ZXBXcndXcmZSYnFUMHJvTW1rQWxtQ3JoM3lzCks0U1J3L0R5b0NPYmJyelpMTVcv
            ODhUMWRCeFlvTHUxZzQ1c05MK2d1TkEKLS0tIG9UM01INjhsc3dMVDU0ODVDLzdR
            RStNNGVqaTlPMk80R1kwa3I3RklvY2sKL7O7E+CfSFbU5ieVaYvZLZcsTvyCHoTd
            GyB0ywMETKt0WbT+1RdiLOnGxJHqjXWAt+3UDlyURXmE+P6zoY4ACA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x5del8md896v3a53z89hss5ktjd0qq4cqlazjd6dkvewjxwy4ufse75yjy
    lastmodified: "2026-07-03T20:56:21Z"
    mac: ENC[AES256_GCM,data:viEaw5x2Orzh68mm7pSVusl/VNvqgtAB68vyFY0/RZZV13epeGFVPQG60Sjbg2DQLF+fcn2LHI4jlUfTDmJKMeY9DiKFwQ8ySdIZV8ejJK/Z47VE6krcxuzglZ2SyYzy4lScidtoq3GAWSGJF4EcyoJNZysf+HLTuCktRPRS8dw=,iv:mQfKH/fJYpTyx1belLOu3+pchYQ7suvjq585iHCUSDs=,tag:qqICyspo3SCPVFzNiNMSdw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
