apiVersion: ENC[AES256_GCM,data:d+8=,iv:LHrsZjEtSqCi11CUek2bnMU+zcZ5CdcDN/3mVWzsoII=,tag:ZIN1fUQr251JrNcB7Edt7A==,type:str]
kind: ENC[AES256_GCM,data:oppyB3YJ,iv:Gnqsqyw/KUk9YyN7iqVHOXC0snWDvqCw6vkCJemKOI0=,tag:sEhO4GWy4L4W6r9RwbZHxQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:hvdW5sVFNxYIVFcTCdNfrRJzNg==,iv:ECiqXl9vJiijRWN6h0mbm0R/eSIFsfS5le2gcef2Jq4=,tag:2XUtypqNNvPgrzubQf0dBg==,type:str]
    namespace: ENC[AES256_GCM,data:Wo7cp+kn,iv:Y28gfjo51qjEYEuiN1vzy0YoESf5Z1sXknzGW2wFd/o=,tag:MHCQBO/wjwaFZJaz1jLzkw==,type:str]
    labels:
        app.kubernetes.io/part-of: ENC[AES256_GCM,data:r+9b46T8,iv:irw2SZ+swoxO1ZXm/q0u4Ls6qemcTZ/buPXMrQFEFps=,tag:Ysbs3DEqi2NNpZkLEVMDbg==,type:str]
stringData:
    token: ENC[AES256_GCM,data:nxF1WfmyN84hkV16lVPJLcC5zFCRH3SHB4D5xLECWHzasiRmj2Tj4FmRUM561Iq5J4fPVyqQdae14i85XMadag==,iv:8vynrE0GtRw3EiEi9uemBEnDhPF32rDuBFICliQCF50=,tag:T6C3h6ldsuZ9NIsCIzyqlg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUQlBWUE9vZWt0cmNBeTQx
            bE1UaEZtSmVzZjhFcUtKQ045TzlORGcwVUE4CmNQZFhHWUtpWHl3NG1TaWQ0V2c5
            eTF4cXFpVS8vR1hnSVRRWUplT1k2VWMKLS0tIDdOeWJBZCtaTWxBZ1NQMXBsbFNN
            UmZLbm9aZ2E3Z2oxZlNPZmR5eDhaS0UKegK/P+ZtPFVTRl47PU3SA2TaQj/LXn4g
            BeJpAqr6eT6358f4mwUDp6U5p7JS7rFW+06ILDv0tmyRx8XJHNKUPA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x5del8md896v3a53z89hss5ktjd0qq4cqlazjd6dkvewjxwy4ufse75yjy
    lastmodified: "2026-07-13T07:20:40Z"
    mac: ENC[AES256_GCM,data:4PW/9IeRJWrCETVmqsw88oWp8Oku3OArzMfsSE8cq8NiQ913GKIgL6klVsBhvqIsnriuyLUOgjbjEpYGjz3PkVxVk8Sc0ukfUfi8ZtMQXFpu4mgGhipoItJGSzY6Ct7ZbHuCxo/A4lDy6hwWbda819Ut4pcJI/hh1WGeRBUgmMY=,iv:TklQTLOXBfdYge8OFKlP2RslpDbrzhobdrlXZCtcxzo=,tag:U/+ej7I8I3yWE8vNa27mNA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
