apiVersion: v1
kind: Service
metadata:
  name: mailpit
  namespace: platform
spec:
  selector:
    app: mailpit
  ports:
    - name: smtp
      port: 1025
      targetPort: smtp
      protocol: TCP
    - name: web
      port: 8025
      targetPort: web
      protocol: TCP
