apiVersion: v1
kind: Service
metadata:
  name: postgres-postgresql
  namespace: platform
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/instance: postgres
spec:
  type: ClusterIP
  ports:
    - name: tcp-postgresql
      port: 5432
      targetPort: tcp-postgresql
      protocol: TCP
  selector:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/instance: postgres
