apiVersion: ENC[AES256_GCM,data:4iU=,iv:umb3urXUCUFuKZWx9LkH9bfkUKLKnpfmDwel3vqJ9qU=,tag:Wqn4u3mMqXA1slLSZdJ6og==,type:str]
kind: ENC[AES256_GCM,data:Z43Im3Zg,iv:t0ipllZInuGGUYEyZtQ24pLv8imGQFNeHDkKES7Wfvk=,tag:xARH31GofYagqZLHSmBX0w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:0jXV/HG/TyAw6q33h9xqLI058A==,iv:k8Az5FiWTKWFi4NZ0DEubuwA5as/skKcK/Hg6eSFZ7U=,tag:p2N96ot6ID0xEUbZ+/vjjA==,type:str]
    namespace: ENC[AES256_GCM,data:Iwwu47MHxpftAw==,iv:VHwu5/B3w5NmezlZTagqTA+rXiZmZYDu9HVFyKBZs+8=,tag:aaHolGgaLfhUkg/rBGCEgA==,type:str]
stringData:
    ARGOCD_PLUGIN_TOKEN: ENC[AES256_GCM,data:fLzz/FIrfSBYJfrYvFAF/VfTc3iBS/NhqfHx6L4xHyjThFIx/6KWDCYm8mg60AXidGDpyQfqNxAK2bHcxOj80A==,iv:+JKUUhULUeFHBqf+wD4bqXxv0YUzhiPyQ0ApPaxQIQw=,tag:jmm406g+At2qssV1m27Xfw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwOGp1a0NWeVdqRk1peGl0
            eTJCbWMyY1VIZkgvcTAvblRFSjZkMFE2aXdVClRiR2NPTWRBRC94UDZ2NHpPeHlV
            cUxuUkpZU3V5cFlsMDYwRExaY1ZTalEKLS0tIHJmUS9SMm5oN1h1RXlUVmIyY0Q4
            alB5c1VxSTA0ZUREaEtvdE5Gb2txOUkKGAAP6Rqu/KG9cQg9TOXQFqSn89/1D4HC
            7pVBHslWd0eVLKLUNRyBmieoy4vq/iTyT4C23MRUBV4pz9Z/pi3nBg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x5del8md896v3a53z89hss5ktjd0qq4cqlazjd6dkvewjxwy4ufse75yjy
    lastmodified: "2026-07-13T07:20:40Z"
    mac: ENC[AES256_GCM,data:tBH2G028BvBo7HTSHmfzgpx4jpQGa5jqPrx+EaslUOrtTtNRFeBiiVPJbuMBUZa6nqKQT7KvsnzlmwNJgHlkp32GOKjm9Gxk9/krcKGOiZASh4szmgvPlmmln6YrF11wq3FmVOQiF13LyD7obXnZXnQ7CeOrC3a6ozj/AoSZRRA=,iv:fVgR46qyJkMn7NXnRt4bi0MbCwaSJTD0H0qBZ9XvcMU=,tag:16hp244pcvh09PwhG01OVQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
