apiVersion: ENC[AES256_GCM,data:w1U=,iv:JazV+gnOCdM7U524UqSEHs3VIqkBjZ66E/1SIPIuZpA=,tag:Y30VHY0IPPtmJV2EsNc0MA==,type:str]
kind: ENC[AES256_GCM,data:6oqE3xHj,iv:UlguTKvtRXZCoNZPwGquqAb1fH1nE7vQiWCoukO8EW4=,tag:uTeF5VLK6UeXAyq0jfg8Bg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:iyAucYD3tj0Hpcv2Qw/oNN71Hg==,iv:AMKFBq9AskKYHhSQ5C6Y6qe+/3t6VZZ7ebegGAKkhL8=,tag:MMuqBuhAX75EvhhVyFTe6Q==,type:str]
    namespace: ENC[AES256_GCM,data:UofD11/sB67pfg==,iv:fTQejeJcCUzOITMjNPXldFJERXz7hEeR9kc8jtkWNbs=,tag:z59SUnbCoXFen/4VUUrhRQ==,type:str]
stringData:
    ARGOCD_PLUGIN_TOKEN: ENC[AES256_GCM,data:J0tRuDXUGkV2PRbO5c4d7bryxilcApAvIE0QVWdtgctofT60nHFFv6+QksS4C3nCcU6jcn7f/Tca0wX3vh8YTg==,iv:ZAxX3KORr388lqPNPy4jKi56Ygnrov2CAXvWFnTXUx8=,tag:QzF4TVYTqhjZw6hJsi8nXA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHU2Vybm1nVko0TVI1R1dl
            eWJZRFhPOGxnTTBjSndwZENMK09wYTl2SmhFCmtEb1hQbVV0aU1ybzM2Y0JzbDR1
            QUxWcitudjVYWWJseXZXTklsSmtUb3cKLS0tIHNDbFlQb0dJQUdkeW13SHhMZVRo
            TXRUZW10cUl3UnBNcUVVODVpNTEwaGMK/pb/LFNT4VxibSLb0QuVf38zfo4VTXV6
            HT9LVxjJsGrFNLkfzG6w8JRbvezcB/jJ+m0J8lZUSrmdXbpcHX4PyA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x5del8md896v3a53z89hss5ktjd0qq4cqlazjd6dkvewjxwy4ufse75yjy
    lastmodified: "2026-07-12T23:02:21Z"
    mac: ENC[AES256_GCM,data:PU3Bjm3Oh0RmLF2AVaBZi04N/p6tVS13pUzuC7DEuPCrA1t2KP8Az3WY1u4yYaU5QF05oK2VFleEYauZkZXhVAMYyFcwMdra09nb3dMGRPQptT524heMvSAGkHbC+0qj6qgH4SV5Dd9DOqbRrprxy6mSytdFZ3UCYUf/uP7qiuE=,iv:DUoYyI1lmOVUKhlJfSr26qxapNtGoe5IpTlfEIrVuoI=,tag:jdoUpBOICL3nEXiC6Oh8Vw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
