apiVersion: ENC[AES256_GCM,data:beM=,iv:OA/xNnseVdsagGuroxrtBKXryqCuwifXZXTUJAbYxrg=,tag:HK+69WOd864a+ViBGEB8qA==,type:str]
kind: ENC[AES256_GCM,data:0pWI673X,iv:gom/xlj5LFh3A4gNQUHKs2wIadUCF9fBC3ri3zozPLk=,tag:gGI/pEf3xu5CLk+byp6u3A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:TZZa4apgcN55w434Pb8ptYtS,iv:U21wzzalpe8DM5sKx+dCLm0lJ53YY1uLw2pWPZq/8oI=,tag:FbTKeo5qoBaqiKuaoAqDGQ==,type:str]
    namespace: ENC[AES256_GCM,data:dxxyzVtxJk4sWA==,iv:Bk/PxaCKO1gDpubaIN0QDsjghF+tQzfMrmj6osQq18I=,tag:0SpqarTlNE3450pZII6+RA==,type:str]
stringData:
    controlCrudToken: ENC[AES256_GCM,data:FFirmq5WxJRDXzi+egs6SC1c8sky/HAP6h5KRUgRRwyw1BOk/HTseg+Q6lhEUR+PDrVGAfL5LSX/rwiyp1IDjw==,iv:3MK0IY1H5N5iv0UzEA9zJ+tuuXuKr8OAY1WvZ9je1/U=,tag:OXqYlb30cY8qAVZ4UtCXow==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOTVRzUTNHTC9zbTVoM2dL
            a1lqUDRZVjV0bThjSUIwQVU2Wm9aSHdvbnp3CllKc0ZnWm1vc2JNaTNKUVo3cGpT
            dnZFelQzQzFvZ0RhcTdJM3VFalB1MUEKLS0tIGgwVDRTOEFxWENOT2t6SGRsUUZM
            cHplWElya0UxRDExWkNXNnhLcTNueFEKYX3NZEtG4S26yOoQXzshqkYpapCV5Ozo
            aB2YQ5ugSXCywyU9pPTJZzYhvZBgjLGPLxcGfKOEJOsF5yys/+ugvw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x5del8md896v3a53z89hss5ktjd0qq4cqlazjd6dkvewjxwy4ufse75yjy
    lastmodified: "2026-07-09T07:30:25Z"
    mac: ENC[AES256_GCM,data:XYKOu/+d49y1tPsEYDikUMZtR9JdnYEGx58gW5J6+u0ZRjw7d11cdrM9jgUbhndjOBe3b+zhAXUsi2WcT0c4DkQl4CtxjHLtLLtbqqs/lEeEnqD4TEH4jo/nYawqlc6x0ADhp6vxrmyPvCodhKev0bKUsCB0mWahn2FtD1KPoZw=,iv:jcmh08g8Xo1mYE6NBWS98tdblcXt8B/zss0/QDr1ObA=,tag:PDvtmMkvmmdHFWoIurNQzw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
