apiVersion: ENC[AES256_GCM,data:ACI=,iv:zjax4AQDTphEdEVL0n5kho3pQtDPpvn1htQ6Iof5VM8=,tag:6YGGkF13JI+cg7O4tPj8WA==,type:str]
kind: ENC[AES256_GCM,data:uzZwzicl,iv:NphSewvvK2A7za3028jxv4CcvfvpmDubffmkFz0S6cY=,tag:dls1tJrKO6EBsl0IurlaDg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Q1wzNkAO5JNcb0kk3iXVKulIWZJJZ9cdJEw=,iv:cOoUAaTjVDzyjlQxVa6/gRZLOt+K/IM3l3+Cwzg3Q7c=,tag:hI7O3FfEGTjIRCpwF1tlMw==,type:str]
    namespace: ENC[AES256_GCM,data:Qwh3ImyYK21/og==,iv:Cl7fNVYlJIW/tnhcQEGnxQg5K25VmvEvJeNqJZGtTDY=,tag:lvMUvj0YwbLV9FpoEU2XAQ==,type:str]
type: ENC[AES256_GCM,data:2xtHEI+A,iv:JgO2BlwoBdp757J6X0hbrJuIniSGk9QzdHd6QqR8wbA=,tag:Dfr+Gcv6xYFyDFMczcCBjA==,type:str]
stringData:
    TEMPORAL_HOST: ENC[AES256_GCM,data:9yXZeZ7iaj1sjULOOFzXQPGzFgPz77R6nMcWiIWwfu57VIo5ehnumw==,iv:Xj930QvVnkhFh7p36dA3LXkgco+aryrsHq5Xu2add/Y=,tag:BU1wONClk3g71OQ0HARruQ==,type:str]
    GRAFANA_HOST: ENC[AES256_GCM,data:bj5AtfHfUB176J620G9ZzoPqInWg6SPCDkSnok9RkwE8kwGSAv2k,iv:bCAVfiMrImJ8ENY2dHMh+FfauQbA59+bVOk0UE6ypU0=,tag:bS7R6v3Y3vEwHQbPaz8oqA==,type:str]
    GRAFANA_USER: ENC[AES256_GCM,data:Cm7/o1w=,iv:x8ZIgFTpBjWLCoTbpj/9rxALcf94qbJkJEqY5hl4V+k=,tag:buO0jNvnZgOa+WDqTqBLpA==,type:str]
    GRAFANA_PASSWORD: ENC[AES256_GCM,data:ypi7eOqWNiCxqxWOWLr9DfvZ9/MIufKjVvfAWpX6czjh5Q9vkVJTy5/zFuNeG/ND,iv:HTgg7pYZW/HBvMjbTj4GHdT41s45FOyyVFAlcV8GPs8=,tag:I2wHA2lCxgDMHxVU/wSp6g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwanJ3bHVQT2l6VXJSRTRL
            TVIzYWgreE1VM1M4NTZOSmtidWFZbFUzQm5JCm1pcWoreGNQZmN6dVNIdUNZZEsz
            UHhNMTN3akx6c0FyVmRPSGQ3OGxQQ1EKLS0tIHAyYlhWalpST3pYVGxITUtoaW9i
            em5qWWNXZXRNY1VTSllNbUxaNVBxMmMK+GeiSSvkMMIPPMl0MtV2YExcZxuAEe4w
            Q6qjF5F7c4Y6UnypekY7HETgRz1C7X6VAfYw330Tk2TaapadyYXYSg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x5del8md896v3a53z89hss5ktjd0qq4cqlazjd6dkvewjxwy4ufse75yjy
    lastmodified: "2026-07-13T12:13:31Z"
    mac: ENC[AES256_GCM,data:l0pZG/8ZBauDSf01R/MDlNR28km4aCEkq+HaIio1MXhkIj/DZ6XCcyoxX4q7ddz8/S/0NaU0RXMZcPm0JhvKwQ0Y1wPXn9Ugv1NuBe1Omahky0Vj+N8bUVhhpwdizOHlswU0RWtcTvb+kgAr19TfwFni0EU1rDD+yZwEfu0cuVc=,iv:bO1dqtPsaiT8j0xhmi7DuONg+n/pFBtbKvgje+/OIwM=,tag:s3w6rrMGucKXWLsi0Jp92g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
