apiVersion: ENC[AES256_GCM,data:M8U=,iv:s8aftfrNpIYV83WpzKq4ZC6AuzU8pGrb4dNYX21plIc=,tag:tpoMVEUOPeTujBVRx/dpYw==,type:str]
kind: ENC[AES256_GCM,data:QI83xfck,iv:V97uyWM3xpvBKNlhD1t11hzDUqWElEm9QCeunLIIDCI=,tag:7ZoAFNnqYELDQH7tcHN5+A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:JSJkL+4/es1aWW0HGVZrp1UBEUN7qA==,iv:L4HXm80iphcK0cCjhMD19xhlfxisEA3BPfM2p0v7oxU=,tag:V4/M7KAvcgVCj5CCxONEng==,type:str]
    namespace: ENC[AES256_GCM,data:8ona0K1XyXfqLw==,iv:Umej5mFwAJIOKUjAYcvEqB+cf1BqqSZFvGbYPQ/Zl78=,tag:NbAl+SSDWLwtfmeimodW2A==,type:str]
stringData:
    privateKey: ENC[AES256_GCM,data:O9GpDDpLe22UrGAls4UOobcQFlXLoZ2SjCQ0P0quqPWEURPDs5yeqjmOdfFGgj/SX2tCRKnBWEuk7YsypxZfww==,iv:mUEjEHEQTRssO6J0m6qxq1MtFMiCvxm7xXgmuoicSZI=,tag:AWMFW71q7jzkAEG69oekyw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsWkkzRm5ETmViQ25yOU01
            K0VOekd5MG9zOHhxL3ByMU9PTmR3a1o1bXlnCnphNkNpdW9kcWRNZVB1RzZObmtn
            VkhqeTBBaFBhYWVaZHV3Q1dYUEJFQ2MKLS0tIENRUTBlVitSN2Z3QzBPT2lUTnJI
            YVlTbSs4UUVFaEtXemdFNmRKQlMwZlEKzqtlwggdqvOLHwP9KE6/WBUZyUf7h7yN
            KVfP3yLx+k9EErewvktEsYnURrtT4BiiYD2K2aYZtVIyrSUaYOclYg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x5del8md896v3a53z89hss5ktjd0qq4cqlazjd6dkvewjxwy4ufse75yjy
    lastmodified: "2026-07-08T21:36:58Z"
    mac: ENC[AES256_GCM,data:MefF4aZ1414Yc57v7LRM/7EqfMTxMjgEGB/070C7s7aJty+q+9b59gJJZ33iE9uLfxrhU+X06Ay3/00AHMB0/1wJVzF0ffcrN+sLOvYHJ60MyVDdtXCBQIBmna5Wjukib7UA47UFw9QD51fIeczxMLk0xA8FVTb86N+eaxKt+zo=,iv:yOP7v9J0At5+RS9FL4jziV2/3IlTmQvvlDrqWDlMUDQ=,tag:bA6jKMp0MT0iqfKymZmWTg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
