apiVersion: ENC[AES256_GCM,data:amE=,iv:ARf+1hlBNuWVNa5Ti9mDRjVY2qb8TNfTuf8O5CW+CCU=,tag:BcfGSkuusMYks9Acs2LtZA==,type:str]
kind: ENC[AES256_GCM,data:nbShCx0+,iv:Ctq5KDIKaJaZMCKlHJJr5pdj3xUKUmbQX0FRs5Ags2E=,tag:3BaLCAPTdTaElIvTv59upg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:MTLOKAdj3vrJ8Ktl9J2itaZI2w==,iv:UkTIJMf5y61V+tswZUb+QGFKgzBmlArlcljzCnSdPCQ=,tag:uKhtSUCOGguIay75Ue0E/Q==,type:str]
    namespace: ENC[AES256_GCM,data:8EY6o+rq8es=,iv:aCo5ttcOLWYVMFceuD5Hlsf2Am1YygmlWkdBk70npSU=,tag:bLQxiQujmsKzJl/juwIiZg==,type:str]
type: ENC[AES256_GCM,data:iM74+BVg,iv:JfZLAAB7yZFfmHx+BTsRcfMAFa40JUzrY9DOM/Njvss=,tag:VWvYmNpTk9yFVGRttlzdig==,type:str]
stringData:
    admin-user: ENC[AES256_GCM,data:4olqqxE=,iv:xHuPVysk02TZdJq2xLbpT4piMj/qbuEyVNlrg0dGFxw=,tag:JHnm4Rhs5gu0QSHmPyYvvw==,type:str]
    admin-password: ENC[AES256_GCM,data:7b/vhjbfKNOUfwkWXj6xIT3Ducji8pGJLUGuHwKW+ASY1j7oAS+z0AVcqdCBDNPg,iv:Dr2TecQ12K/2xe82U1dXmZemGiZCPqPfiI2r6XgslI4=,tag:IhLCI5iMUKuKBgIpDiQxxg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIWkhTeUE2aFlKOGRyNHVu
            UEE0R1lidFFGS1o2R2FxS2dVMUw0bGlBTlcwClRVcVZmdkhVVno3SFBCcGR2NTJz
            VEx3U0ExVWc5bm9ZdGF3aDZiY3J0azgKLS0tIGpZa1pzcG5KbysxVjd4L0czMlFs
            bjFTYVVYdGgvbkhxNFVERGJZMnhkUlkK9QSgKqnwCwQZyGPDuxSkcUcLc0XRCZnK
            h7P/plmdb9w/tg41N0WEIgoZU30QU9ApVxyJr3odLHTJgwK8KurBdA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x5del8md896v3a53z89hss5ktjd0qq4cqlazjd6dkvewjxwy4ufse75yjy
    lastmodified: "2026-07-06T21:51:25Z"
    mac: ENC[AES256_GCM,data:mj+hFhO5P0cpUj3JV9Kq0GatqFTX8pZcdIl4Gnuu1ZIwamHjw7TnyqVmiZq3SknnKyIqLQSjhEorHpmHaZxSOYM9vmmiaebaUBu0vDD6r6pm+Hcfusqx0nhl4RsSs6bEKQi5Bo7xjPuZgEbd+DwB082NzcoSTJyEPDUDMTGOpsA=,iv:jqcTW3nWbQK32jr327oLzseOX3S+0Af/pSWpyfgBKFw=,tag:O7S36x45ALNEPXEUnlel8w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
