apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: engine
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: oci://gitactions.est1908.top/agentic-ops
      chart: engine
      targetRevision: "0.0.0-dcf3d060900c83a830c6bd5eff7f760f902d7b5a"
      helm:
        releaseName: engine
        valueFiles:
          - $values/clusters/ops/engine/values.yaml
    - repoURL: git@github.com:flair-hr/agentops-platform.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: dev-agents
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
