apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: temporal
    repo: https://go.temporal.io/helm-charts
    version: 0.74.0
    releaseName: temporal
    namespace: platform
    valuesFile: values.yaml
