apiVersion: ENC[AES256_GCM,data:fRs=,iv:iate9Q/G3yxblfuOBt2RuXg1fObfKab22l9mY71u5QU=,tag:uN5q1WCHL9j/n4G2BEIqxA==,type:str]
kind: ENC[AES256_GCM,data:ks6aYcQl,iv:usDhJJemDKocgWqEx/Sf3Mh1DPL4gG1Ym7sIC2JynQI=,tag:8c57/6Vk67foBITzooverg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:WpYuPau0ZztAHTyyX0AyBbYpDVYzZQ==,iv:z3+BKD7w4SuMzyWfa3QkCb7xuFnPofTxDoueweIyvcU=,tag:cDxUkyhW31z/avscQrqMPg==,type:str]
    namespace: ENC[AES256_GCM,data:rknnN0nBov0=,iv:sIJWDYXNiOtN8t7VurXsR3FaeBC6mqHcKWeFutnhtoI=,tag:vgihh5WOXRSav23iqu0V8A==,type:str]
type: ENC[AES256_GCM,data:sNpxO9Hn,iv:4RAhVHWl00FcOnlo/ycUa7MNp+nMtBg11YfCxFyvWNA=,tag:5HDkTQSV6uvOcyQmH8AT0w==,type:str]
stringData:
    username: ENC[AES256_GCM,data:JPi/9J0yJw==,iv:SVfHJVTVkJ3YBrOgEnqO4aaTedJvHpIhFixymrMq/y4=,tag:vqPKgt5NhgKEeXw3gAeioQ==,type:str]
    password: ENC[AES256_GCM,data:ZZfNXtTWkTRun6qeK+oXJ9u6keZb4k9A1Sw49X7FOZa6lJtnz2n+pVU1Pospu8p+W/CsE/oKeyPjDLp7kUWegw==,iv:XYFKibXM+XOaoSk1UEDiTZiKt2cFlKyuifn0dmfuPfE=,tag:EneIBab41bJwKB/ZeP7wcQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0eld3YzdNUU5OU3VmaTRt
            R3FacUMrOGU0TlNBUEp4VFJPdzlQZkdvR1hRCklpaXp2RzVIK2xVS1IwR0ZoZFp1
            NzBVeGk3S1AzL1VXTkpybXZ3ZCt0YUkKLS0tIDZVM2szc3dNODVqOTZSUDNHWUp3
            Q1gzdjFFQkVCUjhkVXR4OGtxdnQ0SHcKWJw8pM3D8XujUbpkqHD/k0u5YAK4nBUS
            bZfj2Ro5gJvQnkFTeV7Kio93GdIIroOE3veZhvdfUH7UhZ8MV7lYCw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x5del8md896v3a53z89hss5ktjd0qq4cqlazjd6dkvewjxwy4ufse75yjy
    lastmodified: "2026-07-07T05:46:07Z"
    mac: ENC[AES256_GCM,data:wCWzTC8SmX1TfU3rOhjzVFoOPGw4CDTjGuMVXtf/wJ9R9qq1riN6iYk0YPnpbE6m028BJpGg/KrVE1kET+kaO/jQNZubq3TvlaFWBoudebZoXLXe13+xcO4k4OLJbKV9ELioGTSApS+ndwp9xfYQPHXa8ilacLlHrhZsb+6qxn4=,iv:oRnU4/o9sYK7HyPV6YhfKuncJ8w56NllFurkK30xZaA=,tag:TdmL1SBZ5H6jJYyaA4oL9Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
