apiVersion: ENC[AES256_GCM,data:PFk=,iv:mmGYtPbAjrHavgUW/frRy5IVFybPR0Gj6nqnxn6dWmE=,tag:L30YebmQwkzPLl2fe5kSaQ==,type:str]
kind: ENC[AES256_GCM,data:+h5KmXzd,iv:/zKtH5xG09lb/t65KI/PwqEznO+6yFVXtTsAwzq4V2M=,tag:NoGm6tzBkE4ngERL4wQ75A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:6OhNXc2s+h3Ls6V9vOOYDNFllg==,iv:Tq6UgS79wgFbYfIbOJeQWq/PTjcJIFv/K1oaxsrjgjI=,tag:g7XW+1cj9B//M3V47eVQSw==,type:str]
    namespace: ENC[AES256_GCM,data:a8LS/neSUfM=,iv:TE7iqa9xiDHNPDVmMcG8GkSbYYdcZ1AxbYMy39v8T8o=,tag:212s/jUOLrDm3sMto9P73A==,type:str]
stringData:
    masterkey: ENC[AES256_GCM,data:Phf4YQS0IN97prX7eDYTL7689JTTCf0uOm3PO1GukmJ1D8J3qnTCUYQL/APGyglENOPx,iv:kgQZnb0dB6HiWr13OxcmpOs49f5bng4TdRpcXU7+uY8=,tag:fc85JHftKNDhOwK8+jzvVA==,type:str]
    LITELLM_SALT_KEY: ENC[AES256_GCM,data:AvJYys/M3Rgpu1t/kfW5ZmMU0tuF7lrJnMjDjZS7hQkto7a4dI5QymanYAw=,iv:8RFro28AKSiGs0pVdY16XIGSMIHPk/qLT0qsxf5+h/Q=,tag:nPf/TGpdkIdBjZoZ6xAl3Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSZ2RzMmJsU2hMek5GWU9I
            dFBtWjRoQ0FseW5BSUFxUGc3ZG9saWdQcEJvCk5UUThjeDd0QWpwcEIwZllvTlpH
            eGUyMldMOUFLVjJRV25ONEppWDJPTkkKLS0tIFcvSnFBUHpudUdqck5WSlp3Z1p6
            QWN0S094V3hrZ0hLbkErQ2YvOU9nZzAKu1U3ZBp2TUUm1gvabShmWJAYFR8CYGT4
            VoIBg+aedPcCsSPOtygRoWpvHmdSg7Tbxa8AwPwXK/OWDMLOp6ZOeA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x5del8md896v3a53z89hss5ktjd0qq4cqlazjd6dkvewjxwy4ufse75yjy
    lastmodified: "2026-07-06T22:34:58Z"
    mac: ENC[AES256_GCM,data:LDozXpVONvKa4dl/aQ/OATiLYB9hSduPC/LKAL/xQ1ngTgFrMGrfXezyEiRmGMKECR8re4VTb3jhp9qxPndxm++OVfdMsMVf0ZHoAbnK65MU9uqk0FBsEBShbHlGyJEjTKExMbJsPXfDSbfgwQRfkY5Zty44q/CfsXTi224t8wk=,iv:o3CVjFmbGdfbrr7aH8jAQE82s61sP0mhTF/+SH196MQ=,tag:IQriSAcY8CBIuNHSJVLjxg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
