apiVersion: ENC[AES256_GCM,data:sRM=,iv:/sg/rNck6xQl2XYoPpqJ01XTTS0y6A1TwAAir0TXRhw=,tag:018Kgt5z/WfxbZJ1zYQGwA==,type:str]
kind: ENC[AES256_GCM,data:bWtFRTg/,iv:BnKPK+Mh8jd6c9Bq5L9+1vdiMbhrUqCz1yOgEdEq/hs=,tag:ebD5gFhY4pLuWDCEv0+Shg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:kx049iPQTZap29nLXlfs4E2o8ykQ,iv:8qIVRlaQe8XSm200f9ocsR/B24PvdWYAW1UC9M7oG9c=,tag:X8oaRYA4afPPkZzI5y5Dyw==,type:str]
    namespace: ENC[AES256_GCM,data:VNZjmS4QKLg=,iv:ogn7JWx76HoMiWv7lQHZ27p77mFxhZpFWvVfXqUWMdQ=,tag:eItQ8MXHBhFlmBHeSafr9g==,type:str]
stringData:
    #ENC[AES256_GCM,data:qPPZ4sVELJJb3kDaGN7V0i66BhsiABnffEZTefzWNY3GsBZmTJOLUEhwfRETGL1EBpJYmHX2WBeMVy3De+89cShisSSJqnLB,iv:j+D2XQ9Z+06vuVgRtgdDo9UotvPg2YHUtTb37ckpXjM=,tag:s1JusjvpCgC7NAFe4Io4OQ==,type:comment]
    #ENC[AES256_GCM,data:xLMoismCmzWWmZTw4a0pXGgBw0HTmn4mlqTXiCtoBeIlxeVJcdFOXYwIjnfk4yPZ4g8pISwmirST84ZFk0E2rbwk/vcv2Trxww==,iv:SybjCZh6Lbo6xSIULXy3g5dEeVQyPzZ886kl+Tf+7NA=,tag:TAE+ABdpb4njJPM9vJsbqQ==,type:comment]
    #ENC[AES256_GCM,data:ExKVnuRbXTCzLuce/pc5e4lcVeqTQdWq4mieNRzmN2vQU7E1U6+5QDr23lZ0SzwRh45l/A/68XJuKF4Pkw==,iv:8LVOtZj7+plziQ2YgZFehKZ2ZQGWkS/Frj8fq1kmgUg=,tag:NmQ9/Ff1pfjMjM28++XyVg==,type:comment]
    ZAI_API_KEY: ENC[AES256_GCM,data:/yUDZ4lnyuCBo+9kkcABerBLWXs1SG5CkXFW4fgRFahyF09TCJUXQ2KRlquWqPRWxQ==,iv:k62s1EkBEqw2q4+qEp7JQjv9nMOuniC2xtdzrV4rOg0=,tag:kNcW2YTHW8Koba0quz6mHA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByNnI2VE5ZeDl4TGFXcjhK
            NEh5TXdCcE96aSt3Zktjd2doQTZLLzVHR1RvCjBsanhvKzRpMjg3WVd3WS83T09F
            UVJTbWRLenBDeTNlZXRiaUJVa2xyYU0KLS0tIFBvVVJ1STFzd1FlMHRaSExoanhm
            R3NNd1Rob3F2VURpOHRLVHBCV3l0dTgKN4J1k/ars/jC6AtOwRILB0JVG8WrO4Yr
            TU+c4DEws1ouKNZ0f5l++VaDOJkt+C4ZYskKULdsHzd4CJfKJlX4xQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x5del8md896v3a53z89hss5ktjd0qq4cqlazjd6dkvewjxwy4ufse75yjy
    lastmodified: "2026-07-08T05:38:15Z"
    mac: ENC[AES256_GCM,data:uaXiOEB7yQizlKnhfuGXnnIHosoefn/GcaXZzbepc18boAnKZkdnf6b0m/CCcUwU4gaf837FCDmfYFYFc9Tn4LmIQpkmKFiucfy4rAn33Hx0qKsNJH5czyt6gXgc737iBqlK+DPcajnn3h/jPhvBN+Te8ow19OQzrbMn/MvurF4=,iv:tmcIFQlz0DvahZRyW2SzFSPmmVakYVoVrvfLhTWBnxg=,tag:EHTcGIA7cYcTqlF8+PFXwQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
