apiVersion: ENC[AES256_GCM,data:pKU=,iv:nWyPSoHQh8lSqnSzrFcra0fNXfniNjjVudkuzanBR4E=,tag:OVPNVaM8FreETgXGx9rjIg==,type:str]
kind: ENC[AES256_GCM,data:mc4flSRQ,iv:UsjUqy+BB0tWyH6EOnZvOU4D8/55xkrIg45pxh3O4Os=,tag:nqD8eiUxKlLNi2ghJGZ7IQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:dE8oVThaor8R/2DgcM9uaQ8LNK8q2A==,iv:AZVpt8QGR+YbSJa2i3UwCLwT6HaH/3oJ+x7ZSMlBNLY=,tag:25jL0pH6N/vS6FLCRjgL1g==,type:str]
    namespace: ENC[AES256_GCM,data:skmGocfRLRM=,iv:WSzzIiZ5N0v3J2KSz1SB+k6UB4r7oN7ra10MHSFhe74=,tag:hb3vs17mSd9zFL+VtkN7yw==,type:str]
stringData:
    username: ENC[AES256_GCM,data:a8jjWpwWWA==,iv:x95MF6nfF+o3piB5MYz0yANky6P7SYuZ+vgPo2NHf2o=,tag:wbbgHWlZ/sHPpXpx4Fhupg==,type:str]
    password: ENC[AES256_GCM,data:9cvj9TsUNjWU5LFjy57KORQqcuzx+DXyQ8mpWYmbQ+k=,iv:Ph2KPPdpEqUA65Jy4EGZ6STfdeEKte9CNo+lY/4FilM=,tag:JBeJTSVSEm9g/rHeQ7LCIg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnMEc4c2RGMUYvU3Z6QUN1
            dVdyaittY2w2Mnh0WklXd1Q1U2xKNzAzL1RJCkJrUjBKL25hbXVMaHViejdVTTdt
            WEVEem0wTE9GV2FlWlQ5S2FoL1Q3a00KLS0tIHRlZnN2aUQrVDFzTnI5elF6VDln
            ZlpES2JDeVpsQ3EyZEtCOWpnOVgrcDQKBk6I+f8bmXIQB2CdBcgT1h0VPxwRlB3x
            pzVzmj831HfPCVntlUL8UQFgWUlFhKfBPvzIsV5rC+9IfEPfYTiTXA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x5del8md896v3a53z89hss5ktjd0qq4cqlazjd6dkvewjxwy4ufse75yjy
    lastmodified: "2026-07-06T22:34:58Z"
    mac: ENC[AES256_GCM,data:OO6Nnuf/djPtojsrTJXuWgaqjcCSIX67zpVdfyhiCbdNr7lmsg0TuVfqd5v7YkvUxlQMEdPOM5Xfi0lI2pVhCB5IclIqB81ao0EwwgemV233NAx8P+X3y/qRhrYFvu1RQjfyVybIe1EqsR+hCiONMaLLHaNEZB6wXAlwufiVpHQ=,iv:w7i5HzCpgzADRS0qLNOu3bcah36rZ29CMxbttTnlfMY=,tag:b/X6Sjm6STspZD8Nc1bHPA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
