apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: litellm-credentials-secret-generator
files:
  - ../../../../secrets/litellm/litellm-credentials.enc.yaml
  - ../../../../secrets/litellm/litellm-db-credentials.enc.yaml
  - ../../../../secrets/litellm/litellm-provider-keys.enc.yaml
