apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: step-certificates
    repo: https://smallstep.github.io/helm-charts/
    version: 1.30.0
    releaseName: step-certificates
    namespace: step-ca
    valuesFile: values.yaml

resources:
  - cluster-issuer.yaml
