apiVersion: apps/v1
kind: Deployment
metadata:
  name: technitium
  namespace: technitium
spec:
  replicas: 1
  selector:
    matchLabels:
      app: technitium
  template:
    metadata:
      labels:
        app: technitium
    spec:
      containers:
        - name: technitium
          image: technitium/dns-server:13.4.0
          ports:
            - name: dns-udp
              containerPort: 53
              protocol: UDP
            - name: dns-tcp
              containerPort: 53
              protocol: TCP
            - name: web
              containerPort: 5380
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /etc/dns
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: technitium-data
