apiVersion: ENC[AES256_GCM,data:IWY=,iv:Dg7+VDgVIfTCrSNOgvvhVAP3meh6l3NeVGBRbmKWG04=,tag:asl8q/pM0a3236TdnSaLEQ==,type:str]
kind: ENC[AES256_GCM,data:1OyfVBtf,iv:hKLzzK30YtTQ7hJUNCZC+6smX+qgeG960s7iqqezWQo=,tag:bTDVLIq7kWiMm9vuwmgWOg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:RP2Ge055E7FA0iLFO4tLftw6,iv:f4h6OmVl1eC5+KkGZ6RtZzjqbfrrfeci+l09Vw5V8z4=,tag:prkThdoJsIRZXSld3HKMHA==,type:str]
    namespace: ENC[AES256_GCM,data:PHuD7JRF1208qQ==,iv:nROvRKy8PFQdlH8xeKP4pzlyKHCuwb3lm1nolxTt+fU=,tag:SNN/E3kDOsNv1DtcCxqR/g==,type:str]
stringData:
    CLAUDE_CODE_OAUTH_TOKEN: ENC[AES256_GCM,data:GHh3/Fqt5ZHTkIC2hr0om4rxL8bkmizwDAyZHynhqWHdjIyF1JL0Ek/g/vVh87cQC+IKd6FSA6aLlLYM0I1oMTxiovoiArbK+tQA7JxFa2J7pkst4tRlPtOnw8x7ShJ/d2ZZHshkEmCQ4nbm,iv:mg8CqTabmSFwWnfJLnYH2ZP/LE6ixaZDPbF1uU+51So=,tag:JaWvtZ6/HblFxVwYLEm0bg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3L2hicCtwWDJNNXUxQ050
            UnZiL1VKV2VNVURpaXpyVmd3TGNFbWRMVlFRCjc0U1JydGN6Y285M2ZLQ2IyMHNN
            eE5OcUJ4TnhmdktjdVZaV2J1M1UxeTQKLS0tIHJTRTVCR2xpZ2g3Rlp4K1Q5a3Np
            NGVWbDJNMytmUzRHdXAxM0ZGUGYxUmsKIrt8xM9OGI1NniFeFOYcw73Leomd0ZbA
            hieuSGfan/Ze8ZTqOWiUhCDbnjCIKvnRfvA5fe7y7APYDPEwzkpxUg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x5del8md896v3a53z89hss5ktjd0qq4cqlazjd6dkvewjxwy4ufse75yjy
    lastmodified: "2026-07-09T05:54:11Z"
    mac: ENC[AES256_GCM,data:7JUc92Rrl1I+8ghGKbX9mScK5k6w3IPJU2IOk9a0oVNZHTJmHHZ+ouggVWLl7ryDf5P3C0Ujb+5wEMA3StAH3IUPF5WRQZMmmMgL56UTo1Hv7zqseF23WRSOsc/l8lAgnfPDgidSHP+G6OxXGV/Z0e35aXOsHy0RLCcpKzQLOqU=,iv:tuSMimbKLE3AnydqirUvXsNLapDuZ59ndWmCmF4Ixzk=,tag:IFDN0qPLAlC9jQWVheBjwg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
