apiVersion: ENC[AES256_GCM,data:7N0=,iv:XZfOeZb4+nRNGXdjD/90mTp+L+lf4eTtDnKfmtBTYPk=,tag:WxX7Pfp3C02Iks4CILPoeQ==,type:str]
kind: ENC[AES256_GCM,data:uLFzohrL,iv:4hEHPtIMtqZNsQhQI4xFhcahIEoQs7u8nP+Gk4n6ZTg=,tag:W/HWidrvVVDrd6AzhvrB8w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:r4/UlPzJ6e12Ahsm5Pc=,iv:WP9zRBc5dpwCbEgKQHcKzvWwOwJxXiEsTYInrDlcUb4=,tag:GPJ9Oimsg7wVa8xzcYAzBw==,type:str]
    namespace: ENC[AES256_GCM,data:mgvu0uXXy3WmRA==,iv:MeXHrotIW0hFCgETunP6228HdsVEiSLIWzAY2cgTpE8=,tag:KAYbcsCOMD0ZkEa/QC7yrA==,type:str]
stringData:
    ZAI_API_KEY: ENC[AES256_GCM,data:qRjb1GEAelFGoPHtg3ODXK3Llc2klPq/IZgA8SFmn1ne6BvM+XdfIIGc8AHkgT04Vw==,iv:s8UsIqNWW5AT7LM0Oex9fhSOkbeRMKhPSUbbIEMsLf4=,tag:EaZM2gD+FMUpX86Q1ghpWA==,type:str]
    OPENROUTER_API_KEY: ENC[AES256_GCM,data:NbeHgZi5i13HLk83WiKJhceKxL4jOakEggOm+qclPSSsVyoAJzormgJreZtT7wKvPLEKrKSFjt60RyTfLx8WkY7Njl4cQxFOfg==,iv:S/mhATSaMECRr2lWHbH4m8hJByOPvYq9D+1ER/Pm4G8=,tag:lTSI5rTtN0B8+IGUdo7rKQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2VWp4S2EvRlVkMkVLYkt2
            aWdNeGNDeEpwd3RmN3h2SGs1WnRBRWJ6bVZ3CkpMZ0pMakdZVDZZQmNBUmc3ZTZF
            ZERJWXJILzVsU3NnVUZjb1VkM016aDQKLS0tIFZ0YXp6U09qbjdNTkZ4b0ZEaHNR
            MS9iOVNQVklTUDE4OTZkcmNCSUNnQzAK6ftTQNywPosID9YDwVGDUcGv8wBgVcLF
            QtKG4tJn6vB+DwiK+aErfgmZXVxmDEolKGJ71BC0IrxtF8qW33WJ5w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1x5del8md896v3a53z89hss5ktjd0qq4cqlazjd6dkvewjxwy4ufse75yjy
    lastmodified: "2026-07-06T18:58:58Z"
    mac: ENC[AES256_GCM,data:7Ukt8TOH2vKUvIyk7hJzbw+JZ8HAZJQAqqtwlLGPQjrxjyAvGeFdkr/x5utudPQB/viyk1urdfm1OUyHeXVLh1TBoDqBsyVdNLS2UFta1TZ2PQS2dzqTZNc/AuKuP0phNXSd8pUuRuIVKZYQoWIw0SamkNAYrqHcX25/Snw6EJY=,iv:i6l6b1s4uGhms1vvCvZZTLGllaeVoIcZBMBTDNEP/YY=,tag:MOAAY4Dlq9Rcz9umV3InOQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
